// front-sample-react/my-app/src/components/Sidebar.js
import React from 'react';
import { NavLink, useLocation } from 'react-router-dom';

const Sidebar = () => {
  const location = useLocation();

  const navItems = [
    { id: 'home', label: 'Главная', icon: '🏠', path: '/' },
    { id: 'docs', label: 'Документы', icon: '📄', path: '/docs' },
    { id: 'map', label: 'Карта', icon: '🗺️', path: '/map' },
    { id: 'contacts', label: 'Справочник', icon: '👥', path: '/contacts' },
    { id: 'profile', label: 'Профиль', icon: '👤', path: '/profile' }
  ];

  return (
    <div className="sidebar">
      <div className="logo">OKB АКС</div>
      <nav className="main-nav">
        {navItems.map(item => (
          <NavLink
            key={item.id}
            to={item.path}
            className={({ isActive }) => 
              `nav-btn ${isActive ? 'active' : ''}`
            }
          >
            <span className="icon">{item.icon}</span>
            <span className="label">{item.label}</span>
          </NavLink>
        ))}
      </nav>
    </div>
  );
};

export default Sidebar;

// front2/Sidebar.vue
<style src="./styles.css">
</style>
<template>
    <div class="sidebar">
    <nav class="main-nav">
                <button class="nav-btn active" onclick="showSection('home')">
                    <span class="icon home"></span>
                    <span class="label">Главная</span>
                </button>
                <button class="nav-btn" onclick="showSection('docs')">
                    <span class="icon docs"></span>
                    <span class="label">Документы</span>
                </button>
                <button class="nav-btn" onclick="showSection('map')">
                    <span class="icon map"></span>
                    <span class="label">Карта</span>
                </button>
                <button class="nav-btn" onclick="showSection('dir')">
                    <span class="icon dir"></span>
                    <span class="label">Справочник</span>
                </button>
                <button class="nav-btn" onclick="showSection('prof')">
                    <span class="icon prof"></span>
                    <span class="label">Профиль</span>
                </button>
            </nav>
    </div>
</template>
